"use client";
import {Suspense,useEffect,useState} from "react"; import {useRouter,useSearchParams} from "next/navigation"; import {FolderGit2,Plus,RefreshCw,X} from "lucide-react";
import {AppHeader} from "@/components/AppChrome"; import {Kanban} from "@/components/Kanban"; import {Badge} from "@/components/ui/badge"; import {Button} from "@/components/ui/button"; import {Input} from "@/components/ui/input"; import {Textarea} from "@/components/ui/textarea"; import {api,type CodingProviderStatus,type Job,type JobStreamMessage,type Project} from "@/lib/api";
function BoardInner(){const params=useSearchParams(),router=useRouter(),projectId=params.get("project"); const [project,setProject]=useState<Project|null>(null),[jobs,setJobs]=useState<Job[]>([]),[provider,setProvider]=useState<CodingProviderStatus|null>(null),[liveConnected,setLiveConnected]=useState(false),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[workingBranch,setWorkingBranch]=useState(""),[workflowName,setWorkflowName]=useState(""),[creating,setCreating]=useState(false),[showCreateForm,setShowCreateForm]=useState(false),[error,setError]=useState<string|null>(null);
const load=async()=>{if(!projectId)return;try{const[p,j,c]=await Promise.all([api.getProject(projectId),api.listJobs(projectId),api.getCodingProviderStatus().catch(()=>null)]);setProject(p);setJobs(j);setProvider(c);setError(null)}catch(e){setError(e instanceof Error?e.message:"Unable to load board")}};
useEffect(()=>{if(!projectId){router.replace("/open");return}void load();const source=new EventSource(api.jobsStreamUrl(projectId));source.onopen=()=>setLiveConnected(true);source.onerror=()=>setLiveConnected(false);source.onmessage=m=>{try{const u=JSON.parse(m.data) as JobStreamMessage;if(u.kind==="snapshot"){setJobs(u.jobs);return}setJobs(c=>c.some(j=>j.job_id===u.job.job_id)?c.map(j=>j.job_id===u.job.job_id?u.job:j):[u.job,...c])}catch{}};return()=>{source.close();setLiveConnected(false)}},[projectId]); if(!projectId)return null;
const reset=()=>{setTitle("");setDescription("");setWorkingBranch("");setWorkflowName("");setShowCreateForm(false)};
return <div className="flex min-h-screen flex-col"><AppHeader left={<span className="hidden truncate text-sm text-muted-foreground sm:inline">{project?.name}</span>} right={<><Badge variant={liveConnected?"success":"outline"}>live · {liveConnected?"connected":"reconnecting"}</Badge>{provider&&<Badge variant={provider.available?"success":"failed"}>{provider.provider} · {provider.available?"ready":"unavailable"}</Badge>}<Button variant="ghost" size="sm" onClick={()=>void load()}><RefreshCw className="size-3.5"/> Refresh</Button><Button variant="ghost" size="sm" onClick={()=>router.push("/open")}><FolderGit2 className="size-3.5"/> Repos</Button></>}/>
<div className="mx-auto w-full max-w-[1600px] px-4 pt-5">{!showCreateForm?<div className="flex items-center justify-between rounded-xl border bg-card px-4 py-3 shadow-xs"><div><p className="text-sm font-medium">Create development job</p><p className="mt-0.5 text-xs text-muted-foreground">Choose a workflow and describe the requirement for {project?.name??"this repository"}.</p></div><Button onClick={()=>setShowCreateForm(true)}><Plus className="size-4"/> New requirement</Button></div>:
<form className="rounded-xl border bg-card p-5 shadow-xs" onSubmit={async e=>{e.preventDefault();if(!title.trim()||!description.trim()||!workingBranch.trim()||!workflowName.trim())return;setCreating(true);setError(null);try{const created=await api.createJob({project_id:projectId,title:title.trim(),description:description.trim(),working_branch:workingBranch.trim(),workflow_name:workflowName.trim()});setJobs(c=>[created,...c.filter(j=>j.job_id!==created.job_id)]);reset()}catch(e){setError(e instanceof Error?e.message:"Unable to create job")}finally{setCreating(false)}}}>
<div className="flex items-start justify-between"><div><p className="text-sm font-semibold">Create development job</p><p className="mt-1 text-xs text-muted-foreground">Repository: <span className="font-medium text-foreground">{project?.name??"Loading…"}</span>{project?.base_branch?` · base ${project.base_branch}`:""}</p></div><Button type="button" variant="ghost" size="sm" onClick={reset} disabled={creating}><X className="size-4"/> Cancel</Button></div>
<div className="mt-5 grid gap-4"><label className="grid gap-1.5"><span className="text-sm font-medium">Title *</span><Input placeholder="Add validation for external payments" value={title} onChange={e=>setTitle(e.target.value)} autoFocus/></label><label className="grid gap-1.5"><span className="text-sm font-medium">Working branch *</span><Input placeholder="feature/payment-validation" value={workingBranch} onChange={e=>setWorkingBranch(e.target.value)} spellCheck={false}/></label><label className="grid gap-1.5"><span className="text-sm font-medium">Workflow *</span><Input placeholder="feature-flow-orchestrator" value={workflowName} onChange={e=>setWorkflowName(e.target.value)} spellCheck={false}/><span className="text-xs text-muted-foreground">Enter the workflow name from the centralized skillskit-workflow repository. No workflow is selected by default.</span></label><label className="grid gap-1.5"><span className="text-sm font-medium">Requirement *</span><Textarea placeholder="Describe the change, constraints, and acceptance criteria." value={description} onChange={e=>setDescription(e.target.value)} rows={10}/></label></div>
<div className="mt-5 flex justify-end gap-2"><Button type="button" variant="outline" onClick={reset} disabled={creating}>Cancel</Button><Button type="submit" disabled={creating||!title.trim()||!workingBranch.trim()||!workflowName.trim()||!description.trim()}><Plus className="size-4"/> {creating?"Starting…":"Start development"}</Button></div></form>}{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}</div>{jobs.length===0?<div className="mx-auto max-w-md px-4 py-24 text-center"><p className="text-sm font-medium">No jobs on the line</p><p className="mt-1 text-sm text-muted-foreground">Add a requirement to start the workflow.</p></div>:<Kanban projectId={projectId} jobs={jobs}/>}</div>}
export default function BoardPage(){return <Suspense><BoardInner/></Suspense>}
